
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api-carros

spring:
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true    show-sql: true
    ddl-aut: update
    database-platform: org.hibernate.dialect.H2Dialect
  datasource: 
    driverClassName: org.h2.Driver 
    url: jdbc:h2:mem:consulta-carros
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
      


